stages:
  - lint
  - security

variables:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python --version
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - export PATH="$HOME/.local/bin:$PATH"
  - export UV_LINK_MODE="copy"
  - uv venv
  - uv pip install --upgrade pip
  - uv pip install ruff bandit detect-secrets
  - source .venv/bin/activate

ruff:
  stage: lint
  script:
    - ruff check --fix .
    - ruff format --check .
  tags:
    - linux

bandit:
  stage: security
  script:
    - bandit -r $CI_PROJECT_DIR -x tests,.venv
  tags:
    - linux

detect_secrets:
  stage: security
  script:
    - detect-secrets scan --all-files --exclude-files '\.git/config' > .secrets.baseline
  tags:
    - linux 
